### ISSUE TITLE
Compilation error with FreeRTOS + LwIP on STM32: storage size of 'mreq' isn't known

### ISSUE THREAD

**Issue by PaulFirs** [cesanta/mongoose#3119]
After upgrading from Mongoose 7.12 to 7.17, I'm encountering compilation errors when using FreeRTOS with LwIP on STM32. 
`mongoose.c:8397:18: error: storage size of 'mreq' isn't known`
The same error occurs even when trying to compile the [example](https://github.com/cesanta/mongoose/tree/master/tutorials/stm32/nucleo-f746zg-cube-freertos-lwip) from the repository in STM32CubeIDE. 

My mongoose_config.h
```c
#if defined(MG_ARCH)
#define MG_STMPACK_ARCH MG_ARCH
#undef MG_ARCH
#elif defined(__GNUC__)
#define MG_STMPACK_ARCH MG_ARCH_NEWLIB
#endif

#define MG_ENABLE_PACKED_FS  1
#define MG_ENABLE_CUSTOM_MILLIS  0
#define MG_ENABLE_MBEDTLS  0
#define MG_ARCH MG_ARCH_FREERTOS
#define MG_STMPACK_NET 1
#define MG_ENABLE_CUSTOM_RANDOM  1
#define MG_ENABLE_CUSTOM_LOG 1

void mg_log_prefix(int level, const char *file, int line, const char *fname);

void mg_log(const char *fmt, ...);

// Translate to Mongoose macros
#if MG_STMPACK_NET == 0
#define MG_ENABLE_TCPIP 1
#elif MG_STMPACK_NET == 1
#define MG_ENABLE_LWIP 1
#elif MG_STMPACK_NET == 2
#define MG_ENABLE_FREERTOS_TCP 1
#elif MG_STMPACK_NET == 3
#define MG_ENABLE_RL 1
#endif

#if MG_ENABLE_PACKED_FS
#define MG_ENABLE_FILE 0
#endif

#define MG_ENABLE_POSIX_FS 0
```

# Environment

- mongoose version: 7.17
- Compiler/IDE and SDK: arm-none-eabi-gcc 14.2.1
- Target hardware/board: STM32F407VE and STM32F746ZG
- Connectivity chip/module: STM32F407VE and STM32F746ZG
- Target RTOS/OS (if applicable): freeRTOS

**Comment by scaprile** [comment]
You are right, looks like lwIP has an unexpected dependency when using multicast.
You can use 7.17 release (`git checkout -b 7.17`), that does not include multicast support; or you can check a commit prior to adding multicast support (`git checkout fb09964`), or you can find the missing dependency.
We'll eventually fix this, of course, just wanting to save you some time in case you're in a hurry; HEAD is were we work and sometimes something bites back
Thank you
