### ISSUE TITLE
fail to build with latest gcc (9.1) on 32 bits arches (i686 and armv7)

### ISSUE THREAD

**Issue by sergiomb2** [cesanta/mongoose#1027]
https://github.com/cesanta/mongoose/blob/master/src/mg_http.c#L2496 fails with [1]
since is in LOG(LL_DEBUG, I just comment LOG to fix the build .

[1]
BUILDSTDERR: In function 'mg_uri_to_local_path',
BUILDSTDERR:     inlined from 'mg_serve_http' at mongoose.c:8564:7:
BUILDSTDERR: mongoose.c:548:7: error: '%.*s' directive argument is null [-Werror=format-overflow=]
BUILDSTDERR:   548 |       cs_log_printf x;                                \
BUILDSTDERR:       |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
BUILDSTDERR:   549 |     }                                                 \
BUILDSTDERR:       |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
BUILDSTDERR:   550 |   } while (0)

**Comment by cpq** [comment]
Could you retry with the latest codebase and reopen if required, please?
