### ISSUE TITLE
examples/multi-threaded cannot compile on Ubuntu 20.04

### ISSUE THREAD

**Issue by szsam** [cesanta/mongoose#2148]
- My goal is: Compile examples/multi-threaded on Ubuntu 20.04
- My actions were: Run `make clean examples`
- My expectation was: No compilation error
- The result I saw: 
```
make[1]: Entering directory '/home/runner/work/mongoose/mongoose/examples/multi-threaded'
cc main.c mongoose.c        -W -Wall -Wextra -g -I.     -o example
/usr/bin/ld: /tmp/cc9Ppdzn.o: in function `start_thread':
/home/runner/work/mongoose/mongoose/examples/multi-threaded/main.c:28: undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:23: example] Error 1
make[1]: Leaving directory '/home/runner/work/mongoose/mongoose/examples/multi-threaded'
make: *** [Makefile:61: examples] Error 1
Error: Process completed with exit code 2.
```
- My question is: Is the `-pthread` option missing?

# Environment

- mongoose version: latest commit 2fd2dff126065d4421c2424bf77a0e27c62e60b4
- Compiler/IDE and SDK: GCC 9.4.0
- Target hardware/board: _?_
- Connectivity chip/module: _?_
- Target RTOS/OS (if applicable): _?_

**Comment by scaprile** [comment]
```
cd examples/multi-threaded
make all EXTRA_CFLAGS=-lpthread
```
